### ISSUE TITLE
error create font face 

### ISSUE THREAD

**Issue by davide92br** [xtech/self-o-mat#1]
I have a problem with launching the application returns me this error how can I fix it?
pi@raspberrypi:~/self-o-mat/build $ ./self_o_mat.app
Loading settings file for box: box_kit_v1
Error loading properties. Using defaults.
Using camera: 
Has Button: 0
Button Port Name: 
Has Flash: 0
Failed to load font "./assets/Hack-Regular.ttf" (failed to create the font face)
Could not load font.
Error starting gui - Exiting.
starting clean up
Cleaned up

**Comment by ClemensElflein** [comment]
Hello,
the app is not finding the Hack-Regular font.

You need to launch the app from the self-o-mat folder:

cd ~/self-o-mat && ./build./self_o_mat.app

Hope that helps!


Best,
Clemens Elflein
