### ISSUE TITLE
Publish self-o-mat controller board source code and schematics

### ISSUE THREAD

**Issue by maehw** [xtech/self-o-mat#13]
Hi @ClemensElflein,

in https://github.com/xtech/self-o-mat/issues/5#issuecomment-973064547 (#5) you've mentioned that ...

>If you are interested to go down this path and document the self-o-mat software, I'd be happy to share the Arduino schematics and software needed to get this to work.

I'd be happy if you could share the schematics and firmware of the self-o-mat controller board (https://shop.self-o-mat.de/einzelteile/28-controller-board.html) and maybe pre-compiled binary/HEX file.

I also have a NeoPixel ring light in my setup which is connected to a Raspberry Pi via an Arduino. The both communicate via serial - so I think my hardware setup is quite to yours with the proprietary hardware. Except that I currently do not have the hardware button (nor the power supply and power switch features) - and my Arduino won't be compatible due to other serial commands.

Publishing code and schematics would make this more accessible for other makers, developers and users. And it would be another step towards open hardware/ open software.

Side note: Using a newer Boost library version will break the build of the self-o-mat software and would need to be fixed (interface of `blocking_reader` <-> `boost` broken: e.g. for me Boost library version 1.71; https://github.com/maehw/self-o-mat/blob/28dc6a909c375df24c70efddf9439709b3419d8a/README.md).
Cheers

**Comment by ClemensElflein** [comment]
@maehw code was added in e0fe08661cbe768ee503f200e4e6763c3938daf8

You need to get the Adafruit NeoPixel library and the PinChangeInterrupt library by NicoHood and then it should run on Arduino Nano without a problem. I'll post the Arduino pinout soon

**Comment by ClemensElflein** [comment]
Here it the pinout to use the software:
| Pin | Function          | Connection                                                                                  |
|-----|-------------------|---------------------------------------------------------------------------------------------|
| 4   | NeoPixel data pin | To NeoPixel data input                                                                      |
| 2   | Trigger Button    | Connect trigger button with a pull-up resistor                                              |
| 3   | ON/OFF Switch     | Connect ON/OFF switch with a pull-up resistor. If not needed, pull to 5V                    |
| 8   | POWER             | Can be used to control PC/screen power. Connect PC/screen via relay or leave open if unused |

**Comment by maehw** [comment]
Thank you Clemens. I'll add some of the stuff (probably in a slightly modified manner) into the wiki.
I currently have an Arduino Uno here. Are you aware of any hardware dependencies in your code base that may lead to issues here so that I should stick to an Arduino Nano?

**Comment by ClemensElflein** [comment]
It should work with the UNO as well since both are based on the ATMEGA328. If you have any issues, just ask in #18, maybe it helps someone else too.

**Comment by ClemensElflein** [comment]
Edit on pinout: ON/OFF needs to be pulled LOW if unused
