### ISSUE TITLE
Newer Boost library version will break the build of the self-o-mat software

### ISSUE THREAD

**Issue by ClemensElflein** [xtech/self-o-mat#17]
@maehw ,
could you provide a PR to fix this?

Thanks!

**Comment by maehw** [comment]
At the moment I could only provide a fix which does exclude the `blocking_reader` (https://github.com/maehw/self-o-mat/commit/27e960fdbad1f9101a65c8f30470527667bf7481). However, this will disallow the usage of the SelfomatController until it is fixed. As soon as I have the Arduino firmware source code available I may want to fix this as a first action.

**Comment by ClemensElflein** [comment]
Added the Arduino code and pinout in #13

**Comment by maehw** [comment]
Good news: it seems that I was able to fix it - at least the build and most parts seem to be working.
Note: The changes are still on my fork only. I'm going to prepare a pull request (probably not too soon, but I will).

```
![DBG][BoothLogic]: Setup has button - searching for connected controller board (via serial)
![DBG][SELFOMAT_CONTROLLER]: Searching controller. Prefix: /dev/ttyACM0
![DBG][SELFOMAT_CONTROLLER]: Connecting to controller at: /dev/ttyACM0
![DBG][SELFOMAT_CONTROLLER]: Waiting for identification
![DBG][SELFOMAT_CONTROLLER]: Using boost version 1.71.0
![ERR][BLOCKING_READER]: error: Operation canceled
![WRN][SELFOMAT_CONTROLLER]: No identification received
![DBG][SELFOMAT_CONTROLLER]: Got a 98
![DBG][SELFOMAT_CONTROLLER]: Found the selfomat controller!
![INF][SELFOMAT_CONTROLLER]: Controller Thread Started
![INF][SELFOMAT_CONTROLLER]: setting loading timed out. retrying..
![INF][SELFOMAT_CONTROLLER]: setting loading timed out. retrying..
```

Running the countdown, busy and idle animations seems to work.
Shutdown of the software also has worked after changing the switch position.
I haven't been sniffing the serial communication.

There may be issues with the settings and identification as it seems (please see the log above).
This may also be true because the EEPROM has not been written initially - but it may also be completely unrelated.
I haven't worked with the web server and application yet.

**Comment by ClemensElflein** [comment]
I think there might be an issue with the buffered reader, since the self-o-mat controller board simply returns the current settings.
If no valid settings are found in the EEPROM (CRC check), then default settings are loaded:
```c++
void BaseState::readSettings() {
  EEPROM.get(0, settings);
  settingsDirty = false;


  // Check, if CRC is OK.
  uint16_t crc = CRC16.ccitt((const uint8_t *) &settings, sizeof(settings) - 2);


  if (crc == settings.crcChecksum) {
    updateSettingDependencies();
    return;
  }


  // load defaults
  settings = default_settings;
  // calculate crc for default settings
  settings.crcChecksum = CRC16.ccitt((const uint8_t *) &settings, sizeof(settings) - 2);
  updateSettingDependencies();
}
```
 Could you add logging to the [void SelfomatController::serialPacketReceived](https://github.com/xtech/self-o-mat/blob/8665485f25b65d284753621a26880d0d196f79b5/src/logic/SelfomatController.cpp#L407) method, so that we can see the raw data sent by the controller board?

**Comment by maehw** [comment]
Hi,
I have added some logging.

```
![DBG][BoothLogic]: Setup has button - searching for connected controller board (via serial)
![DBG][SELFOMAT_CONTROLLER]: Searching controller. Prefix: /dev/ttyACM0
![DBG][SELFOMAT_CONTROLLER]: Using boost version 1.71.0
![DBG][SELFOMAT_CONTROLLER]: Connecting to controller at: /dev/ttyACM0
![DBG][SELFOMAT_CONTROLLER]: Waiting for identification (#0)
![DBG][BLOCKING_READER]: Sending request (size: 3)
![DBG][BLOCKING_READER]: timeout
![DBG][BLOCKING_READER]: read complete: bytes_transferred=0
![ERR][BLOCKING_READER]: boost error message: Operation canceled
![WRN][SELFOMAT_CONTROLLER]: No identification received
![DBG][SELFOMAT_CONTROLLER]: Waiting for identification (#1)
![DBG][BLOCKING_READER]: Sending request (size: 3)
![DBG][BLOCKING_READER]: read complete: bytes_transferred=1
![DBG][SELFOMAT_CONTROLLER]: Got character 'b'
![DBG][SELFOMAT_CONTROLLER]: Found the selfomat controller!
![INF][SELFOMAT_CONTROLLER]: Controller Thread Started
![INF][SELFOMAT_CONTROLLER]: setting loading timed out. retrying..
![INF][SELFOMAT_CONTROLLER]: setting loading timed out. retrying..
![DBG][SELFOMAT_CONTROLLER]: serialPacketReceived: bytes_transferred=16
![DBG][SELFOMAT_CONTROLLER]: encoded.size()=15
![DBG][SELFOMAT_CONTROLLER]: Encoded: 0x0f 0x24 0x00 0x10 0x00 0xb8 0x0b 0x10 0x27 0x00 0x00 0x00 0xff 0x25 0xc5
![DBG][SELFOMAT_CONTROLLER]: decoded.size()=14
![DBG][SELFOMAT_CONTROLLER]: Decoded: 0x24 0x00 0x10 0x00 0xb8 0x0b 0x10 0x27 0x00 0x00 0x00 0xff 0x25 0xc5
![DBG][SELFOMAT_CONTROLLER]: Settings loaded
```
It seems that both the identification command and the settings read command both require two attempts to succeed.
I've also dumped the received encoded/decoded bytes. However, I am not perfectly sure if the output is correct (I am rather used to C's `printf` statements instead of some magic byte vectors/sequences).

**Comment by maehw** [comment]
Merge request provided, see #20 :)
