### ISSUE TITLE
Add Fritzing graphic for Arduino Connection

### ISSUE THREAD

**Issue by ClemensElflein** [xtech/self-o-mat#19]
It would be nice to include a [Fritzing](https://fritzing.org/) graphic for the pinout described [in the wiki](https://github.com/xtech/self-o-mat/wiki/Controller-board#wiring).

**Comment by maehw** [comment]
First try, open for improvement suggestions.

![self-o-mat_breadboard](https://user-images.githubusercontent.com/6305922/143502205-e5549660-5638-40a4-9489-a117230c53f7.png)

Also added to the wiki: https://github.com/xtech/self-o-mat/wiki/Controller-board#wiring

Not sure if you head the use of a breadboard in mind or not.

**Comment by ClemensElflein** [comment]
Thank you, this looks good! Exactly as I imagined it. This will help newcomers to get started easily.

**Comment by maehw** [comment]
> Thank you, this looks good! Exactly as I imagined it. This will help newcomers to get started easily.

Curved wires might even look better, but that's the next possible improvement. I was not aware of that feature respectively need to check if my Fritzing version already supports that.

**Comment by ClemensElflein** [comment]
I am also new to Fritzing, but I do like the graphics since they communicate hardware setups in a very simple way. I think the graphic you created is more than enough for a beginner to get the wiring correct, but if you like you can of course adapt it.

**Comment by maehw** [comment]
You are right... I'll add a comment in the wiki for now as I just realized that I didn't modify the default resistor's value ans 220 Ohms does not seem to be an appropriate value for a pull-up/down resistor.  :facepalm:

**Comment by ClemensElflein** [comment]
True, I missed that as well.
