### ISSUE TITLE
Startup File

### ISSUE THREAD

**Issue by ClemensElflein** [xtech/self-o-mat#22]
there are some issues with the way the software is started right now:

- You cannot start the software simply by starting the binary, since not all resources are loaded correctly (web app).
- You cannot start the software by calling start.sh since start.sh is intended to be used in the final deployment and will set CAMLIBS to the wrong value on "normal" systems.

I think we should edit the software in such a way that we can start the binary directly and the start.sh script is only used on "original" self-o-mat deployments. The only change necessary at the moment would be to add an environment variable for the app path which defaults to "web/www" and set it to "./app" in the start.sh file.

**Comment by ClemensElflein** [comment]
@maehw,
it turns out that we already hat a CMAKE target in place which copies the assets needed to run the self-o-mat software to the target folder.. Until now you'd have to specify it manually.

I have now added a dependency to the default target and therefore the assets get copied automatically. Therefore we don't need any start up script for DIY setups or dev setups anymore.

I have updated the readme and you should be able to build and run the software with the web app using the commands.

**Comment by maehw** [comment]
I now get the following error messages when building and running from master:

```
![INF][BUFFERS]: Allocated new buffer with size:8719488
![DBG][BOOTH_GUI]: Recreating texture to fit the new image
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) ../modules/core/src/matrix.cpp:465: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

![INF][MAIN]: starting clean up
![INF][API]: Stopping the API
![INF][MAIN]: We need to stop the logic
![INF][BoothLogic]: stopping logic. Update mode was: 0
![DBG][BoothLogic]: waiting for logic
![INF][BoothLogic]: Syncing changes to disk
![INF][BoothLogic]: Syncing done
![INF][SELFOMAT_CONTROLLER]: Controller Thread stopping...
![INF][SELFOMAT_CONTROLLER]: Controller Thread stopped
![DBG][BoothLogic]: waiting for cam
![INF][GPHOTO CAMERA]: Stopping camera!
![DBG][GPHOTO CAMERA]: some other event. Type was:0
![DBG][GPHOTO CAMERA]: some other event. Type was:0
![DBG][GPHOTO CAMERA]: some other event. Type was:0
![DBG][GPHOTO CAMERA]: some other event. Type was:0
![DBG][BoothLogic]: waiting for print
terminate called recursively
```

But I think this is related to the template files which I have created manually (both PNG and JSON files). I'll take a look into this as it will need more context. But it may also be related to the changes regarding the web app. What do you think?

**Comment by ClemensElflein** [comment]
@maehw 
Yes, the first error originate from invalid template files.

We should investigate the shutdown tho. I have tried it on my system and I have no problem shutting down the app. All modules are shut down correctly and then the executable terminates.

- Did you try to shut down using CTRL+C or using the hardware switch on the Arduino?
- Where does the log "terminate called recursively" come from?

Please start a new issue for this so we can investigate there.

**Comment by maehw** [comment]
It took me a moment to realize that fixing the startup issue also changed something else: I've update the wiki about the settings JSON files. I was very puzzled that making changes after a build/ before a new build did not apply inside of ./settings - but they are copied to ./build/settings as it seems:

https://github.com/xtech/self-o-mat/wiki/Configuration#settings

**Comment by ClemensElflein** [comment]
Yes, that is true. The script copies all needed assets (settings files, font, app data) to the build folder so that the software finds it.
